[bot]
token="7790711628:AAF936a5wvHC9Mly4Kj7bQrOtf40Jmn1Bog"

[bot.chats]
[bot.chats.messages]
id="-1002442269142"
thread=1677
[bot.chats.errors]
id="-1002399905806"
thread=2

[yougile]
token="AiVM8gIRKb4LF4IpcQkyo6X3oAbIZZquOKH7LdrgZ57g6WWsgrd5ULyU47KMHF7g"

[users]
Arctic_Fox_00="dima.zvyagin.00@mail.ru"
SaraAlekseeva="saramaxal@gmail.com"
Polina_Butova="p.butova2014@yandex.ru"
katiekizz="kat.kizilova@gmail.com"
Mkontor="kontor.m@mail.ru"
GhostOfAksandez="aksandez@gmail.com"
viermis="shikabane1@gmail.com"
expad22="expadofficial@yandex.ru"

[process]
update_columns_interval=180
check_interval=15

[notice]
columns_ignore = [
  "???",
  "Идеи",
  "Слухи"
]
tabs_ignore = [
  "???"
]
columns_ready = [
  "Готово"
]
